### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jesskfullwood** [mithodin/rust-nlopt#1]
Hi,

I have a need for nlopt bindings and was going to write some myself, but then I found this repo and it looks like it would be a good starting point, at least. Would you be happy to add a license so others are safe to use it?

Thanks

**Comment by mithodin** [comment]
I will, but I am not sure this is a good base to start from. It was more of an experiment to learn rust than anything else. That being said, feel free to do whatever you want with this.

**Comment by jesskfullwood** [comment]
Thanks!

**Comment by mithodin** [comment]
Sure thing. If you end up developing this into something useful, I would love to hear about it. I might even put in some more work on my end to get this up to speed. Last time I tried it, it was way slower than the pure C version.

**Comment by jesskfullwood** [comment]
Hi, don't know if you've seen my fork but it's up on [crates.io](https://crates.io/crates/nlopt) now and working nicely for my purposes. (crate.io didn't allow the unlicense so I changed it to MIT, hope you don't mind). Haven't benchmarked against pure-C yet, but because Rust allows safe multithreading my actual optimization runs many times faster (thanks, rayon!).

Be interested in your comments!

Ps if you'd like me to remove you name etc, no prob just let me know

**Comment by mithodin** [comment]
Fantastic. I will test a bit over the weekend maybe. Having the name is fine, if maybe a bit undeserved ^^
Looks like your changes effectively amount to a complete rewrite.
